spkcspider/apps/spider/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (
    OwnerTokenManagement, ComponentCreate, ComponentIndex,
    ComponentPublicIndex, ComponentUpdate, ConfirmTokenUpdate, ContentAccess,
    ContentAdd, ContentIndex, EntityMassDeletion, RequestTokenUpdate,
    TokenDeletionRequest, TokenRenewal, TravelProtectionManagement
)

app_name = "spider_base"

# components plural: most components url retrieve multiple items
#    one "component"-url for single retrievals is confusing

urlpatterns = [
    path(
        'components/export/',
        login_required(ComponentIndex.as_view(scope="export")),
        name='ucomponent-export'
    ),
    path(
        'components/slug:user>/export/',
        login_required(ComponentIndex.as_view(scope="export")),
        name='ucomponent-export'
    ),
    path(
        'components/list/',
        login_required(ComponentIndex.as_view()),
        name='ucomponent-list'
    ),
    path(
        'components/list/<slug:user>/',
        login_required(ComponentIndex.as_view()),
        name='ucomponent-list'
    ),
    # path(
    #     'ucs/create/<slug:user>/',
    #     ComponentCreate.as_view(),
    #     name='ucomponent-add'
    # ),
    path(
        'components/add/',
        login_required(ComponentCreate.as_view()),
        name='ucomponent-add'
    ),
    path(
        'components/<str:token>/update/',
        login_required(ComponentUpdate.as_view()),
        name='ucomponent-update'
    ),
    path(
        'components/<str:token>/delete/',
        EntityMassDeletion.as_view(),
        name='entity-delete'
    ),

    path(
        'components/<str:token>/list/',
        ContentIndex.as_view(),
        name='ucontent-list'
    ),
    path(
        'components/<str:token>/export/',
        ContentIndex.as_view(scope="export"),
        name='ucontent-export'
    ),
    path(
        'components/<str:token>/add/<slug:type>/',
        ContentAdd.as_view(),
        name='ucontent-add'
    ),
    path(
        'content/<str:token>/<slug:access>/',
        ContentAccess.as_view(),
        name='ucontent-access'
    ),
    path(
        'token/<str:token>/delete/',
        OwnerTokenManagement.as_view(scope="delete"),
        name='token-owner-delete'
    ),
    path(
        'token/<str:token>/share/',
        OwnerTokenManagement.as_view(scope="share"),
        name='token-owner-share'
    ),
    path(
        'token/confirm-update-request/',
        ConfirmTokenUpdate.as_view(),
        name='token-confirm-update-request'
    ),
    path(
        'token/update-request/',
        RequestTokenUpdate.as_view(),
        name='token-update-request'
    ),
    path(
        'token/delete-request/',
        TokenDeletionRequest.as_view(),
        name='token-delete-request'
    ),
    path(
        'token/renew/',
        TokenRenewal.as_view(),
        name='token-renew'
    ),
    path(
        'travelprotection/',
        TravelProtectionManagement.as_view(),
        name='travelprotection-manage'
    ),
    path(
        'components/',
        ComponentPublicIndex.as_view(
            is_home=False
        ),
        name='ucomponent-listpublic'
    ),
]

spkcspider/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.urls import include, path
from django.views.decorators.cache import cache_page
from django.views.generic.base import RedirectView
from spkcspider.apps.spider.functions import admin_login
from spkcspider.apps.spider.sitemaps import sitemaps
from spkcspider.apps.spider.views import ComponentPublicIndex
from spkcspider.utils.settings import get_settings_func

favicon_view = RedirectView.as_view(
    url='{}spider_base/favicon.svg'.format(settings.STATIC_URL), permanent=True
)
robots_view = RedirectView.as_view(
    url='{}spider_base/robots.txt'.format(settings.STATIC_URL), permanent=True
)

# disable admin login page
admin.site.login = lambda *args, **kwargs: admin_login(
    admin.site, *args, **kwargs
)
# default: allow only non faked user with superuser and staff permissions
admin.site.has_permission = lambda *args, **kwargs: get_settings_func(
    "HAS_ADMIN_PERMISSION_FUNC",
    "spkcspider.apps.spider.functions.has_admin_permission"
)(admin.site, *args, **kwargs)

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '',
        ComponentPublicIndex.as_view(
            is_home=True, template_name="spider_base/home.html"
        ),
        name="home"
    ),
    path('i18n/', include('django.conf.urls.i18n'))
]

for app in apps.get_app_configs():
    url_path = getattr(
        app, "spider_url_path",
        None
    )
    if not url_path:
        continue
    urlpatterns.append(
        path(
            url_path,
            include("{}.urls".format(app.name))
        )
    )


if getattr(settings, "SPIDER_LEGACY_REDIRECT", False):
    urlpatterns.insert(
        0,
        path(
            'spider/content/<int:token1>/<str:token2>/<slug:access>/',
            RedirectView.as_view(
                url='/spider/content/%(token1)s_%(token2)s/%(access)s/',
                permanent=True
            )
        )
    )
    urlpatterns.insert(
        0,
        path(
            'spider/components/<int:token1>/<str:token2>/list/',
            RedirectView.as_view(
                url='/spider/components/%(token1)s_%(token2)s/list/',
                permanent=True
            )
        )
    )
    urlpatterns.insert(
        0,
        path(
            'spider/content/access/<int:token1>/<str:token2>/<slug:access>/',
            RedirectView.as_view(
                url='/spider/content/%(token1)s_%(token2)s/%(access)s/',
                permanent=True
            )
        )
    )
    urlpatterns.insert(
        0,
        path(
            'spider/ucs/list/<int:token1>/<str:token2>/',
            RedirectView.as_view(
                url='/components/%(token1)s_%(token2)s/list/',
                permanent=True
            )
        )
    )


if getattr(settings, "USE_CAPTCHAS", False):
    urlpatterns.append(path(r'captcha/', include('captcha.urls')))

if 'django.contrib.flatpages' in settings.INSTALLED_APPS:
    urlpatterns.append(
        path('pages/', include('django.contrib.flatpages.urls'))
    )

urlpatterns += [
    # daily
    path('favicon.ico', cache_page(86400)(favicon_view)),
    path('robots.txt', cache_page(86400)(robots_view)),
    # daily
    path(
        'sitemap.xml',
        cache_page(86400)(
            sitemaps_views.index
        ),
        {
            'sitemaps': sitemaps,
            'sitemap_url_name': 'sitemaps'
        },
        name='django.contrib.sitemaps.views.index'
    ),
    # hourly
    path(
        'sitemap-<section>.xml',
        cache_page(3600)(
            sitemaps_views.sitemap
        ),
        {'sitemaps': sitemaps},
        name='sitemaps'
    ),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

spkcspider/utils/urls.py
__all__ = (
    "merge_get_url", "extract_host", "replace_action"
)

import re
from urllib.parse import parse_qs, urlencode, urlsplit, urlunsplit

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

_check_scheme = re.compile(r'^[a-z]+://', re.I)


def extract_host(url):
    url = url.lstrip(":/")
    if _check_scheme.search(url) is None:
        urlparsed = urlsplit("://".join(("https", url)))
    else:
        urlparsed = urlsplit(url)
    return "://".join(urlparsed[:2])


def merge_get_url(_url, **kwargs):
    if not _url.isprintable():
        raise ValidationError(
            _("Url contains control characters"),
            code="control_characters"
        )
    _url = _url.lstrip(":/")
    if _check_scheme.search(_url) is None:
        urlparsed = urlsplit("://".join(("https", _url)))
    else:
        urlparsed = urlsplit(_url)
    _strip = []
    for i in kwargs.keys():
        if not kwargs[i]:
            _strip.append(i)
    GET = parse_qs(urlparsed.query)
    GET.update(kwargs)
    for item in _strip:
        GET.pop(item, None)
    ret = urlunsplit((*urlparsed[:3], urlencode(GET, doseq=True), ""))
    return ret


def replace_action(url, action):
    url = url.split("?", 1)
    # urljoin does not join correctly, removes token because of no ending /
    return "%s?%s" % (
        "%s/%s" % (
            url[0].rstrip("/").rsplit("/", 1)[0], action.lstrip("/")
        ),
        url[1] if len(url) >= 2 else ""
    )

spkcspider/apps/spider/forms/flatpages.py
__all__ = ["FlatpageItemForm"]

import copy

from django.contrib.flatpages.forms import FlatpageForm
from django.utils.translation import gettext_lazy as _

from ..widgets import TrumbowygWidget

_help_text = _(
    """Example: '/about/contact/'. Make sure to have leading and trailing slashes.
    <br/>Special Urls (ordered by url):<br/>
    /home/heading/*/ : flatpages used for heading on frontpage <br/>
    /home/main/*/ : flatpages used for general information on frontpage <br/>
    /gfooter/*/ : flatpage links with general informations (links will be rendered on every page)
    """  # noqa: E501
)


class FlatpageItemForm(FlatpageForm):
    url = copy.copy(FlatpageForm.base_fields["url"])
    url.help_text = _help_text

    class Meta(FlatpageForm.Meta):
        widgets = {
            "content": TrumbowygWidget()
        }

spkbspider/apps/spider/views/components.py
__all__ = ("ComponentIndex", "ComponentAllIndex", "ComponentCreate", "ComponentUpdate", "ComponentDelete")

from django.views.generic.detail import BaseDetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.db import models
from django.http import HttpResponseRedirect
from django.conf import settings
from django.utils import timezone

from .core import UserTestMixin, UCTestMixin
from ..forms import UserComponentForm
from ..contents import installed_contents
from ..models import UserComponent, UserContent

from datetime import timedelta

class ComponentAllIndex(ListView):
    model = UserComponent
    is_home = False

    def get_context_data(self, **kwargs):
        #kwargs
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        q = models.Q(protected_by__isnull=True)&~models.Q(name="index")
        if self.request.user.is_authenticated:
            q |= models.Q(user=self.request.user)
        if "search" in self.request.GET:
            q &= models.Q(name__icontains=self.request.GET["search"])
        return self.model.objects.filter(q)

    def get_paginate_by(self, queryset):
        return getattr(settings, "COMPONENTS_PER_PAGE", 25)


class ComponentIndex(UCTestMixin, ListView):
    model = UserComponent

    def test_func(self):
        if self.has_special_access(staff=True):
            return True
        return False

    def get_queryset(self):
        ret = self.model.objects.filter(user=self.get_user())
        if "search" in self.request.GET:
            ret = ret.filter(name__icontains=self.request.GET["search"])
        return ret

    def get_usercomponent(self):
        return get_object_or_404(UserComponent, user=self.get_user(), name="index")

    def get_paginate_by(self, queryset):
        return getattr(settings, "COMPONENTS_PER_PAGE", 25)

class ComponentCreate(PermissionRequiredMixin, UserTestMixin, CreateView):
    model = UserComponent
    permission_required = 'spiderucs.add_usercomponent'
    form_class = UserComponentForm

    def get_form_kwargs(self):
        ret = super().get_form_kwargs()
        #ret["initial"]["user"] = self.get_user()
        ret["instance"] = self.model(user=self.get_user())
        return ret
class ComponentUpdate(UserTestMixin, UpdateView):
    model = UserComponent
    form_class = UserComponentForm

    def get_context_data(self, **kwargs):
        kwargs["available"] = installed_contents.keys()
        kwargs["assigned"] = self.object.contents.all()
        return super().get_context_data(**kwargs)

    def get_object(self, queryset=None):
        if queryset:
            return get_object_or_404(queryset, user=self.get_user(), name=self.kwargs["name"])
        else:
            return get_object_or_404(self.get_queryset(), user=self.get_user(), name=self.kwargs["name"])

class ComponentDelete(UserTestMixin, DeleteView):
    model = UserComponent
    fields = []
    http_method_names = ['get', 'post', 'delete']

    def get_required_timedelta(self):
        _time = getattr(settings, "UC_DELETION_PERIOD", {}).get(self.object.name, None)
        if not _time:
            _time = getattr(settings, "DEFAULT_DELETION_PERIOD", None)
        if _time:
            now = timezone.now()
            _time = timedelta(seconds=_time)
        else:
            _time = timedelta(seconds=0)
        return _time

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        _time = self.get_required_timedelta()
        if _time and self.object.deletion_requested:
            now = timezone.now()
            if self.object.deletion_requested+_time>=now:
                kwargs["remaining"] = timedelta(seconds=0)
            else:
                kwargs["remaining"] = self.object.deletion_requested+_time-now
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        # deleting them should not be possible, except by deleting user
        if self.object.is_protected:
            return self.handle_no_permission()
        _time = self.get_required_timedelta()
        if _time:
            now = timezone.now()
            if self.object.deletion_requested:
                if self.object.deletion_requested+_time>=now:
                    return self.get(request, *args, **kwargs)
            else:
                self.object.deletion_requested = now
                self.object.save()
                return self.get(request, *args, **kwargs)
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.deletion_requested = None
        self.object.save(update_fields=["deletion_requested"])
        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, queryset=None):
        if queryset:
            return get_object_or_404(queryset, user=self.get_user(), name=self.kwargs["name"])
        else:
            return get_object_or_404(self.get_queryset(), user=self.get_user(), name=self.kwargs["name"])

spkbspider/apps/spider/views/core.py
__all__ = ("UserTestMixin", "UCTestMixin")

from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.core.exceptions import ImproperlyConfigured, PermissionDenied

from ..models import UserComponent

class UserTestMixin(UserPassesTestMixin):

    # by default only owner can access view
    def test_func(self):
        if self.has_special_access(staff=False, superuser=False):
            return True
        return False

    def has_special_access(self, staff=False, superuser=True):
        if self.request.user == self.get_user():
            return True
        if superuser and self.request.user.is_superuser:
            return True
        if staff and self.request.user.is_staff:
            return True
        return False

    def get_user(self):
        username = None
        if "user" in self.kwargs:
            username = self.kwargs["user"]
        elif self.request.user.is_authenticated:
            username = self.request.user.username
        return get_object_or_404(get_user_model(), username=username)

    def get_usercomponent(self):
        return get_object_or_404(UserComponent, user=self.get_user(), name=self.kwargs["name"])

    #def get_noperm_template_names(self):
    #    return [self.noperm_template_name]

    #def handle_no_permission(self):
    #    raise PermissionDenied(self.get_permission_denied_message())

class UCTestMixin(UserTestMixin):
    usercomponent = None

    def dispatch(self, request, *args, **kwargs):
        self.usercomponent = self.get_usercomponent()
        user_test_result = self.get_test_func()()
        if not user_test_result:
            return self.handle_no_permission()
        return super(UCTestMixin, self).dispatch(request, *args, **kwargs)

spkcspider/apps/spider/templates/spider_base/usercomponent_list_fragment.html
{% load i18n static spider_base spider_rdf %}
<table class="w3-table w3-bordered" rel="spkc:components">
  {% if table_heading %}
  <thead>
    <tr>
      <th colspan="3">
        {{table_heading}}
      </th>
    </tr>
  </thead>
  {% endif %}
  <tbody>
  {% for uc in object_list %}
    <tr class="color-front-{% if request.is_special_user %}{{uc.strength}}{% else %}{{uc.untrusted_strength}}{% endif %}" resource="{% url 'spider_base:ucontent-list' token=uc.token %}" typeof="spkc:Component">
      <td class="{% if uc.is_index %}w3-large{% endif %}" style="min-height:48px;display:inline-block;word-break: break-all;">
        <data hidden="hidden" property="spkc:type" datatype="xsd:string">Component</data>
        <data hidden="hidden" property="spkc:strength" datatype="xsd:integer">{% if request.is_special_user %}{{uc.strength}}{% else %}{{uc.untrusted_strength}}{% endif %}</data>
        <data rel="spkc:properties">
          <data typeof="spkc:Property">
            <data hidden="hidden" property="spkc:name" datatype="xsd:string">name</data>
            {% if uc.is_index and request.is_owner %}
              <span property="spkc:value" datatype="xsd:string">{% trans 'Private Component' %}</span>
            {% else %}
              <span property="spkc:value" datatype="xsd:string">{{ uc.name }}</span>{% if not request.user == uc.user %} <em>({{uc.user}})</em>{% endif %}
            {% endif %}
          </data>
          <data hidden="hidden" typeof="spkc:Property">
            <data hidden="hidden" property="spkc:name" datatype="xsd:string">user</data>
            <data hidden="hidden" property="spkc:value" datatype="xsd:string">{{uc.username}}</data>
          </data>
          <data hidden="hidden" typeof="spkc:Property">
            <data hidden="hidden" property="spkc:name" datatype="xsd:string">description</data>
            <data hidden="hidden" property="spkc:value" datatype="xsd:string">{{uc.description|escape}}</data>
          </data>
          <data hidden="hidden" typeof="spkc:Property">
            <data hidden="hidden" property="spkc:name" datatype="xsd:string">features</data>
            <data hidden="hidden" property="spkc:value">
              {% for f in uc.features.all %}
                <data datatype="xsd:string">{{f.name}}</data>
              {% endfor %}
            </data>
          </data>
        </data>
      </td>
      <td>
        {% blocktrans trimmed with time=uc.modified|timesince %}
        Modified: {{time}} ago
        {% endblocktrans %}
      </td>
      <td style="display:inline-block">
        <div class="w3-bar w3-round-large w3-tiny w3-blue">
          <a style="{% if request.user == uc.user %}width:50%{% else %}width:100%{% endif %}" class="w3-hover-black w3-button w3-bar-item w3-tooltip w3-mobile" href="{% url 'spider_base:ucontent-list' token=uc.token %}">
            <div class="spkc-entity-button"><i class="fas fa-list-ul" alt="{% trans 'List' %}" aria-label="{% trans 'List' %}"></i></div>
            <div aria-hidden="true" class="w3-text w3-black spkc-entity-button-text"><div class="w3-animate-opacity">{% trans "List" %}</div></div>
          </a>
          {% if request.user == uc.user %}
            <a style="width:50%" rel="nofollow" class="w3-hover-black w3-button w3-bar-item w3-tooltip w3-mobile" href="{% url 'spider_base:ucomponent-update' token=uc.token %}" property="spkc:action:update">
              <div class="spkc-entity-button"><i class="fas fa-edit" alt="{% trans 'Edit' %}" aria-label="{% trans 'Edit' %}"></i></div>
              <div aria-hidden="true" class="w3-text w3-black spkc-entity-button-text"><div class="w3-animate-opacity">{% trans "Edit" %}</div></div>
            </a>
          {% endif %}
        </div>
      </td>
    </tr>
    <tr><td colspan="3" style="padding:0; word-break: break-all;">
      <div class="w3-white w3-padding w3-border-bottom" style="{% if not forloop.last %}margin-bottom:20px{% endif %}">
        {% if not uc.description|is_not_or_space %}
          {{uc.description|escape|linebreaksbr}}
        {% else %}
          <span class="w3-text-gray">{% trans 'No description' %}</span>
        {% endif %}
      </div>
    </td></tr>
  {% empty %}
      <tr><td><data hidden="hidden" resource="rdf:nil"/>{% trans 'No Components available.' %}</td></tr>
  {% endfor %}
  </tbody>
</table>

spkcspider/apps/spider/templates/spider_base/usercontent_access.html
{% extends "spider_base/ucs_base.html" %}
{% load i18n %}

{% block title %}{% if scope == "add" %}{% blocktrans trimmed with name=object %}
  Create Content: {{name}}
{% endblocktrans %}{% elif scope == "update" %}{% blocktrans trimmed with name=object %}
  Update Content: {{name}}
{% endblocktrans %}{% else %}{% blocktrans trimmed with name=object %}
  Content: {{name}}
{% endblocktrans %}{% endif %}{% endblock %}

{% block context_actions %}
{{block.super}}
{% endblock context_actions %}
{% block main_classes %}w3-padding w3-content w3-card-4 w3-pale-green{% endblock %}

{% block content %}
  <div>
    <a class="w3-left" href="{% url 'spider_base:ucontent-list' id=uc.id nonce=uc.nonce %}?{{request.GET.urlencode}}">{% trans 'index' %}</a>
    {% if scope != "add" and request.user == uc.user %}
      <span class="w3-right">
        <div style="margin-bottom:10px">
          <a href="{% url 'spider_base:ucontent-remove' user=uc.username name=uc.name nonce=object.nonce id=object.id %}">
            {% trans 'Delete' %}
          </a>?
        </div>
        {% if scope != "view" %}
        <div>
          <a class="" href="{% url 'spider_base:ucontent-access' id=object.id nonce=object.nonce access='view' %}?{{spider_GET.urlencode}}">
            {% trans "View" %}
          </a>
        </div>
        {% endif %}
      </span>
    {% endif %}
    <h1 class="w3-center">
      {% if scope == "add" %}
        {% blocktrans trimmed with name=object %}
          Create Content: <em>{{name}}</em>
        {% endblocktrans %}
      {% elif scope == "update" %}
        {% blocktrans trimmed with name=object %}
          Update Content: <em>{{name}}</em>
        {% endblocktrans %}
      {% else %}
        {% blocktrans trimmed with name=object %}
          Content: <em>{{name}}</em>
        {% endblocktrans %}
      {% endif %}
    </h1>
  </div>
{% if form %}
  {{form.media}}
  {% if not render_in_form %}
  <details>
    <summary class="w3-btn w3-grey">
      <i class="fa fa-plus" style="margin-right:10px" aria-hidden="true"></i>
      {% trans 'Base Settings' %}
      <i class="fa fa-caret-down" style="margin-left:5px" aria-hidden="true"></i>
    </summary>
    {% endif %}
    {% include "spider_base/form_errors.html" with form=form %}
    <form action="{{ request.get_full_path }}" enctype="{{enctype}}" method="post">
      {% csrf_token %}
      <fieldset>
        <legend><h2>{% trans 'Content Settings' %}</h2></legend>
        {% include "spider_base/base_form.html" with form=form %}
      </fieldset>
      {% if content and render_in_form %}
        <fieldset>
          <legend><h2>{% if scope == "add" %}{{object}}{% else %}{{object.associated.ctype}}{% endif %}</h2></legend>
          {{content|safe}}
        </fieldset>
      {% endif %}
      <button class="w3-button w3-grey">
        {% if scope == "add" %}
          {% trans 'Create' %}
        {% else %}
          {% trans 'Update' %}
        {% endif %}
      </button>

      {% if scope != "add" %}
        <a class="w3-right" href="{% url 'spider_base:ucontent-access' id=object.id nonce=object.nonce access='view' %}?{{request.GET.urlencode}}">
          {% trans "View" %}
        </a>
      {% endif %}
    </form>
  {% if not render_in_form %}
  </details>
  {% endif %}
{% endif %}
{% if object.id and UserContentType.raw_update in associated.ctype %}
  <div>
    <a class="w3-button" href="{% url 'ucontent-access' id=object.id nonce=object.nonce access='raw_update' %}">
      <i class="fa fa-settings" aria-hidden="true"></i>
      {% trans 'Update Raw Content' %}
    </a>
  </div>
{% endif %}
{% if not render_in_form %}{{content|safe}}{% endif %}
{% endblock %}

spkcspider/apps/spider/templates/spider_base/usercontent_list.html
{% extends "spider_base/ucs_base.html" %}
{% load i18n %}
{% block title %}{% blocktrans trimmed with name=uc.name %}
    Content of: {{name}}
  {% endblocktrans %}{% endblock %}

{% block main_classes %}{{block.super}} w3-content w3-card-4{% endblock %}

{% block content %}
  <div>
    {% if request.user == uc.user %}
      <a class="w3-right" href="{% url 'spider_base:ucomponent-update' name=uc.name nonce=uc.nonce %}">Update</a>
    {% endif %}
    <h1 class="w3-center">
      {% blocktrans trimmed with name=uc.name %}
        Content of Component: <em>{{name}}</em>
      {% endblocktrans %}
    </h1>
  </div>
  {% if uc.user == request.user %}
    <details class="" style="margin-bottom:30px" {% if object_list|length < 2 %}open="open"{% endif %}>
      <summary class="w3-button w3-hover-dark-grey w3-black">
        <i class="fa fa-plus" style="margin-right:10px" aria-hidden="true"></i>
        {% trans 'Add new content' %}
        <i class="fa fa-caret-down" style="margin-left:5px" aria-hidden="true"></i>
      </summary>
      <div class="w3-padding w3-border">
        <div class="w3-row">
          {% for contentt in content_types %}
            <a class="w3-button w3-col s12 m3 w3-grey" href="{% url 'spider_base:ucontent-add' user=uc.user name=uc.name type=contentt.name %}">
              <b style="margin-right:5px" aria-hidden="true">+</b>{{contentt}}
            </a>
          {% empty %}
              {% trans 'No User Content Types available.' %}
          {% endfor %}
        </div>
      </div>
    </details>
  {% endif %}
  <table class="w3-table w3-striped w3-bordered w3-hoverable w3-margin">
    {% for content in object_list %}
      <tr>
        <td class="">
          {{ content.content|truncatechars:50 }}
        </td>
        <td class="w3-show-inline-block">
          <div class="w3-bar w3-round-large w3-tiny w3-blue">
            <a class="w3-hover-black w3-button w3-bar-item w3-tooltip" href="{% url 'spider_base:ucontent-access' id=content.id nonce=content.nonce access='view' %}?{{spider_GET.urlencode}}">
              <i class="fa fa-eye" alt="{% trans 'View' %}" aria-label="{% trans 'View' %}"></i>
              <span aria-hidden="true" style="position:absolute;left:1px;bottom:2px" class="w3-text w3-black w3-large"><span class="w3-animate-opacity">{% trans "View" %}</span></span>
            </a>
            {% if uc.user == request.user  %}
            <a class="w3-hover-black w3-button w3-bar-item w3-tooltip" href="{% url 'spider_base:ucontent-access' id=content.id nonce=content.nonce access='update' %}">
              <i class="fa fa-edit" alt="{% trans 'Edit' %}" aria-label="{% trans 'Edit' %}"></i>
              <span aria-hidden="true" style="position:absolute;left:1px;bottom:2px" class="w3-text w3-black w3-large"><span class="w3-animate-opacity">{% trans "Edit" %}</span></span>
            </a>
            <a class="w3-hover-black w3-button w3-bar-item w3-tooltip" href="{% url 'spider_base:ucontent-remove' user=content.usercomponent.username name=content.usercomponent.name id=content.id  nonce=content.nonce %}">
              <i class="fa fa-trash" alt="{% trans 'Delete' %}" aria-label="{% trans 'Delete' %}"></i>
              <span aria-hidden="true" style="position:absolute;left:1px;bottom:2px" class="w3-text w3-black w3-large"><span class="w3-animate-opacity">{% trans "Del" %}</span></span>
            </a>
            {% endif %}
          </div>
        </td>
      </tr>
    {% empty %}
      <tr><td>{% trans 'No User Content available.' %}</td></tr>
    {% endfor %}
  </table>
  <div class="page-manipulation w3-padding" style="margin-top:40px">
    {% include 'spider_base/list_footer.html' %}
  </div>
{% endblock %}